# Python first code
### import this

In [116]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [1]:
print("Hello Part!!")

Hello Part!!


# Python data types

### boolean, int, float, complex, string, None

In [2]:
b = True
print(b)
print(type(b))
b = 1.1
b, type(b)

True
<class 'bool'>


(1.1, float)

In [3]:
i = 2
i, type(i)

(2, int)

In [4]:
f = .5
f, type(f)

(0.5, float)

In [5]:
c = 1 + 3j
c, type(c)

((1+3j), complex)

In [6]:
s = 'mammad "folanja" inja'
print(s)

mammad "folanja" inja


## Strings

### plus, index, startswith, conditions, find, ...

In [7]:
s1 = "abc"
s2 = "123"
print(s1)
print(s2)

abc
123


In [8]:
s12 = s1 + s2
s12

'abc123'

In [9]:
type(s12)

str

In [10]:
s12.index("23")

4

In [11]:
s12.endswith("23")

True

In [12]:
s12.startswith("ab")

True

In [13]:
"vvv" in s12

False

In [14]:
s12.find("bbbb")

-1

# Python Lists

In [15]:
my_list = [1, 2, 3, 4.1, "mammad", "part", ["hassan", 3.3]]
my_list, type(my_list)

([1, 2, 3, 4.1, 'mammad', 'part', ['hassan', 3.3]], list)

In [16]:
len(my_list)

7

### append and extend

In [17]:
my_list.append("test append")
my_list

[1, 2, 3, 4.1, 'mammad', 'part', ['hassan', 3.3], 'test append']

In [18]:
test_list = ["extend1", "extend2"]
my_list.append(test_list)
my_list

[1,
 2,
 3,
 4.1,
 'mammad',
 'part',
 ['hassan', 3.3],
 'test append',
 ['extend1', 'extend2']]

In [19]:
my_list.extend(test_list)
my_list

[1,
 2,
 3,
 4.1,
 'mammad',
 'part',
 ['hassan', 3.3],
 'test append',
 ['extend1', 'extend2'],
 'extend1',
 'extend2']

In [20]:
my_list = my_list + test_list
my_list

[1,
 2,
 3,
 4.1,
 'mammad',
 'part',
 ['hassan', 3.3],
 'test append',
 ['extend1', 'extend2'],
 'extend1',
 'extend2',
 'extend1',
 'extend2']

### insert, remove, pop, ...

In [21]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [22]:
my_list.insert(2, 2.5)
my_list

[1, 2, 2.5, 3]

In [23]:
my_list.insert(0, 3.5)
my_list

[3.5, 1, 2, 2.5, 3]

In [24]:
my_list.remove(3.5)
my_list

[1, 2, 2.5, 3]

In [25]:
my_list.pop()
my_list

[1, 2, 2.5]

In [26]:
len(my_list)

3

In [27]:
my_list = [1, 2, 3]
my_list[1]

2

In [28]:
rt_value = my_list.pop(1)
print(my_list)
print(rt_value)

[1, 3]
2


### sub list

In [29]:
my_list = [1, 2, 3, 4, 5, "a", "b", "c"]
sub_list = my_list[2:7]
sub_list

[3, 4, 5, 'a', 'b']

In [30]:
sub_list_2 = my_list[2:]
sub_list_2

[3, 4, 5, 'a', 'b', 'c']

In [31]:
sub_list_3 = my_list[1::2]
sub_list_3

[2, 4, 'a', 'c']

### unpacking

In [32]:
a, b, c, d = sub_list_3

In [33]:
print(a)
print(b)

2
4


### copy a list

In [34]:
my_list_copy = my_list.copy()
my_list_copy[1] = 200
print(my_list)
print(my_list_copy)

[1, 2, 3, 4, 5, 'a', 'b', 'c']
[1, 200, 3, 4, 5, 'a', 'b', 'c']


# Tuple

In [35]:
tpl = (50, 1)
tpl, type(tpl)

((50, 1), tuple)

In [36]:
my_tp = ("a", "b", "c")
my_tp

('a', 'b', 'c')

### Tuples are immutable

In [37]:
# my_tp[1] = "dd"

### How to change Tuples

In [38]:
my_tp_list = list(my_tp)
my_tp_list[1] = "dd"
my_tp = tuple(my_tp_list)
my_tp

('a', 'dd', 'c')

# Python Dictionary

In [39]:
my_dict = {"key1": 23, "key2": 48, "key3": 12, 12: 112}
my_dict

{'key1': 23, 'key2': 48, 'key3': 12, 12: 112}

In [40]:
my_dict[12]

112

### update dictionary

In [41]:
my_dict["key2"] = 1112
my_dict

{'key1': 23, 'key2': 1112, 'key3': 12, 12: 112}

In [42]:
my_dict["key4"] = "test"
my_dict

{'key1': 23, 'key2': 1112, 'key3': 12, 12: 112, 'key4': 'test'}

# Numpy

In [43]:
import numpy as np
import tensorflow as tf

2025-02-13 12:02:33.925416: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-13 12:02:33.926740: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 12:02:33.931178: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 12:02:34.052431: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739435554.160944    6312 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739435554.18

## Converting a python list to a numpy array

In [44]:
np_arr = np.array([[1, 2.], [4, 5.]])
np_arr

array([[1., 2.],
       [4., 5.]])

In [45]:
tf_tensor = tf.convert_to_tensor([[1., 2.], [4, 5]])
type(tf_tensor)

W0000 00:00:1739435569.694955    6312 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


tensorflow.python.framework.ops.EagerTensor

In [46]:
tf_tensor.shape

TensorShape([2, 2])

In [47]:
tf_tensor.dtype

tf.float32

In [48]:
tf_int_tensor = tf.cast(tf_tensor, dtype=tf.int32)
tf_int_tensor.numpy()

array([[1, 2],
       [4, 5]], dtype=int32)

In [49]:
empty_arr = np.array([])
empty_arr.shape

(0,)

In [50]:
np_arr.shape

(2, 2)

In [51]:
np_arr.dtype

dtype('float64')

In [52]:
np_arr.size

4

In [53]:
np_arr.ndim

2

In [54]:
np_arr.strides

(16, 8)

## Some useful functions in numpy

### arange, zeros, ones, eye, linspace, ...

In [55]:
np_arr = np.arange(2, 30, 4)
np_arr

array([ 2,  6, 10, 14, 18, 22, 26])

In [56]:
np_z = np.zeros((3, 4), dtype=np.float32)
np_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [57]:
tf_z = tf.zeros((3, 4), dtype=np.float32)
tf_z

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [58]:
np_o = np.ones((4, 3))
np_o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np_arr = np.linspace(2, 30, 6)
np_arr

array([ 2. ,  7.6, 13.2, 18.8, 24.4, 30. ])

## Random arrays using numpy

### rand, randn, randint, seed, ...

In [60]:
rand_arr = np.random.rand(3, 4)
rand_arr

array([[0.86683129, 0.37049989, 0.13990364, 0.1722704 ],
       [0.13724213, 0.811749  , 0.64593279, 0.92603548],
       [0.54506115, 0.52020653, 0.76260115, 0.0078488 ]])

In [61]:
tf.random.set_seed(46)
rand_tf = tf.random.uniform(shape=(4, 10), maxval=1., dtype=tf.float32)
rand_tf

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 , 0.41742086, 0.8905815 ],
       [0.04490781, 0.64715993, 0.6124575 , 0.8963598 , 0.50094795,
        0.5403452 , 0.13583767, 0.796286  , 0.11443329, 0.6610137 ],
       [0.75864327, 0.05791759, 0.9041784 , 0.5926819 , 0.14621067,
        0.10904384, 0.28547847, 0.65069926, 0.09890389, 0.7398746 ],
       [0.56936777, 0.7675011 , 0.27471685, 0.72731483, 0.69775176,
        0.50558805, 0.98601305, 0.7327801 , 0.85814536, 0.04894578]],
      dtype=float32)>

In [62]:
rand_arr = np.random.uniform(low=10.0, high=50.0, size=(3, 4))
rand_arr

array([[26.26019506, 34.26927021, 11.88496237, 22.57953007],
       [33.13689835, 46.19872673, 22.96764029, 14.76882962],
       [28.95965522, 32.85319595, 16.86121117, 10.03537328]])

In [63]:
rand_arr = np.random.randn(3, 4)
rand_arr

array([[-0.10134903,  1.08003634,  1.45054807, -0.97879526],
       [-1.18176097,  0.20460896,  0.8101561 ,  1.78071109],
       [ 1.02420316, -0.03571494,  2.2597968 ,  0.40157256]])

In [64]:
np.random.seed(43)
rand_arr = np.random.rand(3, 4)
rand_arr

array([[0.11505457, 0.60906654, 0.13339096, 0.24058962],
       [0.32713906, 0.85913749, 0.66609021, 0.54116221],
       [0.02901382, 0.7337483 , 0.39495002, 0.80204712]])

In [65]:
np.random.seed(43)
rand_arr = np.random.rand(3, 4)
rand_arr

array([[0.11505457, 0.60906654, 0.13339096, 0.24058962],
       [0.32713906, 0.85913749, 0.66609021, 0.54116221],
       [0.02901382, 0.7337483 , 0.39495002, 0.80204712]])

In [66]:
rand_arr2 = np.random.rand(3, 4)
rand_arr2

array([[0.25442113, 0.05688494, 0.86664864, 0.221029  ],
       [0.40498945, 0.31609647, 0.0766627 , 0.84322469],
       [0.84893915, 0.97146509, 0.38537691, 0.95448813]])

## Cast and Reshape a numpy array

In [67]:
rand_arr.dtype

dtype('float64')

In [68]:
rand_arr = rand_arr.astype(np.float32)
rand_arr.dtype

dtype('float32')

In [69]:
reshape_arr = np.reshape(rand_arr, newshape=(6, -1))
reshape_arr

array([[0.11505456, 0.60906655],
       [0.13339096, 0.24058962],
       [0.32713905, 0.8591375 ],
       [0.6660902 , 0.5411622 ],
       [0.02901382, 0.7337483 ],
       [0.39495003, 0.80204713]], dtype=float32)

In [70]:
reshape_arr.dtype, reshape_arr.shape

(dtype('float32'), (6, 2))

In [71]:
tf_reshape = tf.reshape(rand_tf, (5, 8))
tf_reshape

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 ],
       [0.41742086, 0.8905815 , 0.04490781, 0.64715993, 0.6124575 ,
        0.8963598 , 0.50094795, 0.5403452 ],
       [0.13583767, 0.796286  , 0.11443329, 0.6610137 , 0.75864327,
        0.05791759, 0.9041784 , 0.5926819 ],
       [0.14621067, 0.10904384, 0.28547847, 0.65069926, 0.09890389,
        0.7398746 , 0.56936777, 0.7675011 ],
       [0.27471685, 0.72731483, 0.69775176, 0.50558805, 0.98601305,
        0.7327801 , 0.85814536, 0.04894578]], dtype=float32)>

## Some statistical functions

### min, max, mean, median(!), argmax, argmin, ... 

In [72]:
reshape_arr.min()

np.float32(0.029013824)

In [73]:
tf.reduce_mean(tf_reshape, axis=0)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([0.34085056, 0.55485314, 0.3144979 , 0.51581055, 0.59111035,
       0.56495744, 0.7100685 , 0.5658175 ], dtype=float32)>

In [74]:
# tf.nn
# tf.math
# tf.

In [75]:
reshape_arr.max()

np.float32(0.8591375)

In [76]:
# reshape_arr.median()

In [77]:
np.median(reshape_arr)

np.float32(0.4680561)

In [78]:
np.argmax(reshape_arr)

np.int64(5)

In [79]:
np.min(reshape_arr, axis=1)

array([0.11505456, 0.13339096, 0.32713905, 0.5411622 , 0.02901382,
       0.39495003], dtype=float32)

# Numpy indexing and selection

In [80]:
np.random.seed(124)
np_arr = np.random.rand(10, 6)
np_arr

array([[0.10606491, 0.74547148, 0.57231354, 0.45824118, 0.3847059 ,
        0.27398931],
       [0.66796241, 0.39547501, 0.28157289, 0.77991971, 0.59909416,
        0.12294636],
       [0.38957403, 0.97498836, 0.4675989 , 0.14017141, 0.04206858,
        0.72799627],
       [0.61560551, 0.9027321 , 0.62263341, 0.2601217 , 0.55551768,
        0.40498648],
       [0.14175587, 0.57774636, 0.52652124, 0.93856912, 0.95887879,
        0.9844318 ],
       [0.23095612, 0.09707925, 0.24574867, 0.69075766, 0.1974319 ,
        0.8295272 ],
       [0.34612727, 0.51401486, 0.66115798, 0.93362449, 0.06690067,
        0.74688969],
       [0.39028262, 0.53575843, 0.06042919, 0.8913558 , 0.77787374,
        0.6701197 ],
       [0.7350527 , 0.66369952, 0.18176625, 0.86299757, 0.45142896,
        0.6497297 ],
       [0.15937201, 0.40598175, 0.79885158, 0.72915428, 0.07090418,
        0.76971324]])

In [81]:
element = np_arr[2, 3]
element

np.float64(0.14017140765011182)

In [82]:
sub_arr = np_arr[2:5, :3]
sub_arr

array([[0.38957403, 0.97498836, 0.4675989 ],
       [0.61560551, 0.9027321 , 0.62263341],
       [0.14175587, 0.57774636, 0.52652124]])

In [83]:
# croped_image = image[20:-20, 30:-30, :]

In [84]:
sub_tensor = tf_reshape[1:4, 4:7]
sub_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6124575 , 0.8963598 , 0.50094795],
       [0.75864327, 0.05791759, 0.9041784 ],
       [0.09890389, 0.7398746 , 0.56936777]], dtype=float32)>

## Conditional Selection

In [85]:
np.random.seed(56)
np_arr = np.random.rand(12)
np_arr

array([0.98419185, 0.33341227, 0.67370162, 0.19639042, 0.35444646,
       0.81336595, 0.24784955, 0.45861133, 0.87730142, 0.39165846,
       0.32613342, 0.09009511])

In [86]:
mask = np_arr > 0.5
mask

array([ True, False,  True, False, False,  True, False, False,  True,
       False, False, False])

In [87]:
np_cond_arr = np_arr[mask]
np_cond_arr

array([0.98419185, 0.67370162, 0.81336595, 0.87730142])

In [88]:
np_cond_arr2 = np_arr[np_arr > 0.5]
np_cond_arr2

array([0.98419185, 0.67370162, 0.81336595, 0.87730142])

In [89]:
mask = tf_reshape > 0.5
mask

<tf.Tensor: shape=(5, 8), dtype=bool, numpy=
array([[ True, False, False, False, False, False,  True,  True],
       [False,  True, False,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True, False,  True,  True],
       [False, False, False,  True, False,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True, False]])>

In [90]:
tf_select = tf_reshape[mask]
tf_select

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([0.7300668 , 0.717703  , 0.8796133 , 0.8905815 , 0.64715993,
       0.6124575 , 0.8963598 , 0.50094795, 0.5403452 , 0.796286  ,
       0.6610137 , 0.75864327, 0.9041784 , 0.5926819 , 0.65069926,
       0.7398746 , 0.56936777, 0.7675011 , 0.72731483, 0.69775176,
       0.50558805, 0.98601305, 0.7327801 , 0.85814536], dtype=float32)>

In [91]:
# tf.gather()

# Numpy Operations via different Axis

### add, substitute, div

In [92]:
np_cond_arr2 = np_cond_arr2 / 2.
np_cond_arr2

array([0.49209593, 0.33685081, 0.40668298, 0.43865071])

In [93]:
np.random.seed(57)
test_array = np_cond_arr2 + np.random.rand(np_cond_arr2.shape[0])
test_array

array([0.57944557, 0.56732791, 0.81774405, 0.74943341])

In [94]:
test_array = test_array - np.ones(shape=np_cond_arr2.shape)
test_array

array([-0.42055443, -0.43267209, -0.18225595, -0.25056659])

### sum and concatenate over axis

In [95]:
np.random.seed(124)
np_arr = np.random.rand(10, 6)
np_arr

array([[0.10606491, 0.74547148, 0.57231354, 0.45824118, 0.3847059 ,
        0.27398931],
       [0.66796241, 0.39547501, 0.28157289, 0.77991971, 0.59909416,
        0.12294636],
       [0.38957403, 0.97498836, 0.4675989 , 0.14017141, 0.04206858,
        0.72799627],
       [0.61560551, 0.9027321 , 0.62263341, 0.2601217 , 0.55551768,
        0.40498648],
       [0.14175587, 0.57774636, 0.52652124, 0.93856912, 0.95887879,
        0.9844318 ],
       [0.23095612, 0.09707925, 0.24574867, 0.69075766, 0.1974319 ,
        0.8295272 ],
       [0.34612727, 0.51401486, 0.66115798, 0.93362449, 0.06690067,
        0.74688969],
       [0.39028262, 0.53575843, 0.06042919, 0.8913558 , 0.77787374,
        0.6701197 ],
       [0.7350527 , 0.66369952, 0.18176625, 0.86299757, 0.45142896,
        0.6497297 ],
       [0.15937201, 0.40598175, 0.79885158, 0.72915428, 0.07090418,
        0.76971324]])

In [96]:
np.sum(np_arr, axis=1)

array([2.54078632, 2.84697054, 2.74239755, 3.36159688, 4.12790319,
       2.2915008 , 3.26871495, 3.32581947, 3.5446747 , 2.93397704])

In [97]:
arr1 = np.random.rand(2, 3, 10)
arr2 = np.random.rand(2, 3, 5)
cc_arr = np.concatenate((arr1, arr2), axis=2)
cc_arr.shape

(2, 3, 15)

# Python Functions and Flow Control

### for and if on a random numpy array

In [98]:
np.random.seed(49)
arr = np.random.rand(16)
for index, element in enumerate(arr):
    if element > 0.5:
        print(element)
    elif element < 0.4:
        print("low element = {} on index = {}".format(element, index))

low element = 0.3009644558559146 on index = 0
low element = 0.24706183196181442 on index = 1
0.9263351350591756
0.891603438277764
0.6832767599749869
0.5668846594996723
0.5469658802430317
low element = 0.21042383598676584 on index = 7
0.7697544681854357
0.8962301009569733
0.7216504565659716
0.8024305278044254
0.8448313057399196
low element = 0.22913820441272792 on index = 15


### define a function in Python

In [99]:
def my_func(value1="no_name", value2=0):

    print("value1 = {}".format(value1))
    print("value2 = {}".format(value2))

    return value1 + "_test", value2 + 1


def my_func(value1="no_name", value2=0):

    print("value1 = {}".format(value1))
    print("value2 = {}".format(value2))

    return value1 + "_test", value2 + 1

In [100]:
value1_plus, value2_plus = my_func(value1="mammad", value2=23)
print(value1_plus)
print(value2_plus)

value1 = mammad
value2 = 23
mammad_test
24


### use our function with multiple output

# Python Class

In [101]:
class MyClass:

    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2
        print("parent init")

    def mtd(self):
        print(self.arg1)
        print(self.arg2)
        print("parent method")


In [102]:
mc = MyClass("mammad", 24)
mc.mtd()

parent init
mammad
24
parent method


## Python Sub-Class

In [103]:
class MySubClass(MyClass):

    def __init__(self, arg1, arg2, arg3):
        super(MySubClass, self).__init__(arg1, arg2)
        self.arg3 = arg3
        print("child init")

    def child_mtd(self,):
        self.mtd()
        print(self.arg3)
        print("child method")

In [104]:
smc = MySubClass("hassan", 25, "alaki")

parent init
child init


In [105]:
smc.child_mtd()

hassan
25
parent method
alaki
child method


## OS and Pickle

In [106]:
import os
import pickle

In [107]:
os.listdir("./")

['test_dir',
 'test_file.txt',
 'my_first_pickle.pkl',
 'testdir',
 'workspace.code-workspace']

In [108]:
for file_name in os.listdir("./"):
    if "numpy" in file_name:
        print(file_name)

In [109]:
if not os.path.exists("test_dir/"):
    os.mkdir("test_dir/")
else:
    print("exists")

exists


In [110]:
os.listdir("./")

['test_dir',
 'test_file.txt',
 'my_first_pickle.pkl',
 'testdir',
 'workspace.code-workspace']

In [111]:
test_dict = {"k1": 1, "k2": 2, "k3": 3}

In [112]:
pickle.dump(test_dict, open("my_first_pickle.pkl", "wb"))

In [113]:
loaded_dict = pickle.load(open("my_first_pickle.pkl", "rb"))
loaded_dict

{'k1': 1, 'k2': 2, 'k3': 3}

#  Read and Write .txt files

In [114]:
names = ["Ali", "Mammad", "Mohsen"]
with open("test_file.txt", "w") as text_file:
    for name in names:
        text_file.write("Name of person = {}\n".format(name))
text_file.close()

In [115]:
read_names = []
with open("test_file.txt", "r") as text_file:
    lines = text_file.readlines()
    for index, line in enumerate(lines):
        print("line {}: {}".format(index, line))
        words = line.split(" ")
        read_names.append(words[-1][:-1])

print(read_names)

line 0: Name of person = Ali

line 1: Name of person = Mammad

line 2: Name of person = Mohsen

['Ali', 'Mammad', 'Mohsen']
