In [39]:
# 1 Import necessary packages

In [1]:
import tensorflow as tf

2025-02-14 16:02:37.099940: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-14 16:02:37.100457: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-14 16:02:37.102633: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-14 16:02:37.109531: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739536357.122273    7954 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739536357.12

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
# 2 Load Boston Housing dataset

In [6]:
(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.boston_housing.load_data()

In [7]:
train_data.ndim, train_data.shape, train_data.dtype, np.any(np.isnan(train_data)), train_data[:5]

(2,
 (404, 13),
 dtype('float64'),
 np.False_,
 array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
         6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
         2.10000e+01, 3.96900e+02, 1.87200e+01],
        [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
         7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
         1.47000e+01, 3.95380e+02, 3.11000e+00],
        [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
         4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
         2.02000e+01, 3.75520e+02, 3.26000e+00],
        [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
         6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
         2.02000e+01, 3.96900e+02, 8.01000e+00],
        [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
         6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
         2.02000e

In [8]:
test_data.ndim, test_data.shape, test_data.dtype, np.any(np.isnan(test_data)), test_data[:5]

(2,
 (102, 13),
 dtype('float64'),
 np.False_,
 array([[1.80846e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.79000e-01,
         6.43400e+00, 1.00000e+02, 1.83470e+00, 2.40000e+01, 6.66000e+02,
         2.02000e+01, 2.72500e+01, 2.90500e+01],
        [1.23290e-01, 0.00000e+00, 1.00100e+01, 0.00000e+00, 5.47000e-01,
         5.91300e+00, 9.29000e+01, 2.35340e+00, 6.00000e+00, 4.32000e+02,
         1.78000e+01, 3.94950e+02, 1.62100e+01],
        [5.49700e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
         5.98500e+00, 4.54000e+01, 4.81220e+00, 5.00000e+00, 2.24000e+02,
         2.02000e+01, 3.96900e+02, 9.74000e+00],
        [1.27346e+00, 0.00000e+00, 1.95800e+01, 1.00000e+00, 6.05000e-01,
         6.25000e+00, 9.26000e+01, 1.79840e+00, 5.00000e+00, 4.03000e+02,
         1.47000e+01, 3.38920e+02, 5.50000e+00],
        [7.15100e-02, 0.00000e+00, 4.49000e+00, 0.00000e+00, 4.49000e-01,
         6.12100e+00, 5.68000e+01, 3.74760e+00, 3.00000e+00, 2.47000e+02,
         1.85000e

In [9]:
train_labels.ndim, train_labels.shape, train_labels.dtype, np.any(np.isnan(train_labels)), train_labels[:5]

(1, (404,), dtype('float64'), np.False_, array([15.2, 42.3, 50. , 21.1, 17.7]))

In [10]:
test_labels.ndim, test_labels.shape, test_labels.dtype, np.any(np.isnan(test_labels)), test_labels[:5]

(1, (102,), dtype('float64'), np.False_, array([ 7.2, 18.8, 19. , 27. , 22.2]))

In [11]:
# 3 Reshape dataset

In [12]:
train_labels = np.reshape(train_labels, newshape=(-1, 1))

In [13]:
test_labels = np.reshape(test_labels, newshape=(-1, 1))

In [14]:
train_labels.shape, test_labels.shape

((404, 1), (102, 1))

In [15]:
# 4 Check min/max data

In [16]:
train_data.min(axis=0), train_data.max(axis=0)

(array([6.3200e-03, 0.0000e+00, 4.6000e-01, 0.0000e+00, 3.8500e-01,
        3.5610e+00, 2.9000e+00, 1.1296e+00, 1.0000e+00, 1.8800e+02,
        1.2600e+01, 3.2000e-01, 1.7300e+00]),
 array([ 88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,   8.725 ,
        100.    ,  10.7103,  24.    , 711.    ,  22.    , 396.9   ,
         37.97  ]))

In [17]:
# 5 Normalize data

In [18]:
# 5.1 Fit

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
min_max_scaler = MinMaxScaler()

In [21]:
min_max_scaler.fit(train_data)

MinMaxScaler()

In [22]:
# 5.2 Transform

In [23]:
train_data = min_max_scaler.transform(train_data)

In [24]:
test_data = min_max_scaler.transform(test_data)

In [25]:
# Check min/max post normalization

In [26]:
train_data.min(axis=0), train_data.max(axis=0)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [27]:
test_data.min(axis=0), test_data.max(axis=0)

(array([ 7.63179629e-05,  0.00000000e+00,  2.78592375e-02,  0.00000000e+00,
         1.44032922e-02,  2.55422153e-01,  3.19258496e-02,  3.50600687e-02,
         0.00000000e+00, -1.91204589e-03,  4.25531915e-02,  6.13495386e-02,
         5.24282561e-03]),
 array([0.28144109, 0.9       , 1.        , 1.        , 1.        ,
        1.01065066, 1.        , 1.14781801, 1.        , 1.        ,
        0.91489362, 1.        , 0.83498896]))

In [28]:
train_labels.min(), train_labels.max()

(np.float64(5.0), np.float64(50.0))

In [29]:
# 6 Change data types

In [30]:
train_data = train_data.astype(np.float32)

In [31]:
train_labels = train_labels.astype(np.float32)

In [32]:
test_data = test_data.astype(np.float32)

In [33]:
test_labels = test_labels.astype(np.float32)

In [34]:
train_data.dtype, test_data.dtype

(dtype('float32'), dtype('float32'))

In [35]:
# 7 Create regression model

In [ ]:
# from tensorflow.keras.models import Model
# model = tf.keras.models.Sequential()

2025-02-14 16:12:05.641904: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-14 16:12:05.642428: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-14 16:12:05.644827: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-14 16:12:05.654305: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739536925.672290   10335 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739536925.67

NameError: name 'tf' is not defined

In [37]:
# from tensorflow.keras.layers import Dense, Input
# dense = tf.keras.layers.Dense()
# input = tf.keras.layers.Input()

In [38]:
# input_layer = input((13, ))